-- [II] SELECT문 - 조회

-- 1.  SELECT문자 작성법(실행:CTRL+ENTER)
SELECT * FROM TAB; 현계정이 가지고 있는 테이블정보
SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;

--2. 특정열만출력
DESC EMP;
  --EMP테이블 구조
SELECT SAL,EMPNO,ENAME,HIREDATE FROM EMP;
SELECT SAL AS "사번",EMPNO AS "사아",ENAME AS "사번",HIREDATE AS "사번" FROM EMP;
SELECT SAL "사번",EMPNO,ENAME "사번",HIREDATE "사번" FROM EMP;

-- 3. 특정 행만 출력 : WHERE절(조건절)에서 비교연산자 
SELECT EMPNO NO,ENAME NAME,SAL FROM EMP WHERE SAL=3000;
SELECT EMPNO NO,ENAME NAME,SAL FROM EMP WHERE SAL<>=3000;
SELECT EMPNO NO,ENAME NAME,SAL FROM EMP WHERE SAL>3000;
    -- 비교연산자
    -- EX1. 사원이름(ENAME)이 'A','B','C'로 시작하는 사원의 모드필드
    SELECT * FROM EMP WHERE ENAME<'D';











